name: Build and Upload APK

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'
      - 'v*.*.*-*' #


permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore keystore file
        run: |
          echo "$RELEASE_KEYSTORE_BASE64" | base64 -d > ./android/app/my-release-key.jks
        env:
          RELEASE_KEYSTORE_BASE64: ${{ secrets.RELEASE_KEYSTORE_BASE64 }}

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        env:
          KEYSTORE_FILE_PATH: my-release-key.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: flutter build apk --release --dart-define=SUPABASE_KEY=$SUPABASE_KEY

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Get tag commit message
        id: get_commit_msg
        run: |
          echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B ${{ github.ref }} >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ env.RELEASE_BODY }}
          draft: false
          prerelease: true
          files: build/app/outputs/flutter-apk/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
